app/Classes/WalletManager.php
app/Http/Controllers/Transfer/Bank/DepositController.php
app/Http/Controllers/Transfer/Bank/TransferController.php
app/Http/Controllers/Transfer/Bank/WithdrawalController.php
app/Http/Controllers/Transfer/User/ReceiveController.php
app/Http/Controllers/Transfer/User/SendController.php
app/Http/Controllers/Transfer/User/TransferController.php
app/Http/Controllers/User/ContactController.php
app/Http/Controllers/User/UserController.php
app/Http/Controllers/Wallet/TransactionController.php
app/Http/Controllers/Wallet/WalletController.php
app/Transformers/UserTransformer.php
app/Transformers/WalletTransformer.php
app/Wallet.php
composer.json
composer.lock
config/app.php
config/laravel-fractal.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2017_02_16_205333_create_wallets_table.php
routes/api.php

- Setup controllers for teammates to fill.
- Integrated [Fratal](https://fractal.thephpleague.com) for api data formatting.
- Integrated [Money](https://github.com/moneyphp/money) for money handling in many currencies.
- Added `WalletManager.php` to be filled.

Controllers

---

database/migrations/2017_02_16_205333_create_wallets_table.php
database/migrations/2017_02_17_013500_create_transactions_table.php

changed format to string

---

.gitignore
app/Contact.php
app/Transfer.php
database/migrations/2017_02_17_184025_create_transfers_table.php
database/migrations/2017_02_22_191119_create_contacts_table.php

Added Transfer and Contact model.

Transfer model

---

app/BankTransfer.php
database/migrations/2017_02_22_202955_create_bank_transfers_table.php
tests/unit/AuthTest.php

Banktransfer model

---

app/Http/Controllers/Transfer/Bank/DepositController.php
app/Http/Controllers/Transfer/Bank/WithdrawalController.php
app/Providers/AppServiceProvider.php
app/Providers/PayPalServiceProvider.php
resources/lang/en/validation.php
tests/unit/TestValidation.php

- Moved paypal methods to the paypal service provider.
- Separated large functions into small function.

Refactor bank controllers

---

app/Http/Controllers/Controller.php
tests/unit/UserTest.php
tests/unit/WalletManagerTest.php
tests/unit/WalletTest.php

- Added white space to tests to increase code readability.
- Forced laravel to return json after validating inputs from requests.

refactor tests - integrate json error response handling

---

app/Providers/NexmoServiceProvider.php
composer.json
composer.lock
config/app.php
config/services.php
routes/api.php

- adds the nexmo service provider to send text messages
- refactoring api.php file

Sms api research

---

app/Http/Responses/JsonErrorResponse.php

A new custom response class that extends the original json response class to return formatted error reponses. It is used to help increase reuseability.

Json error response

---

app/Http/Controllers/Auth/LoginController.php
composer.lock

you must decode the url, and json to reach the data.
Example url:
```
http://localhost:8000/api/app/callback?data=%7B%22data%22%3A%7B%22id%22%3A2%2C%22name%22%3A%22Laurendy+Lam%22%2C%22email%22%3A%22lamlaurendy%40gmail.com%22%2C%22username%22%3Anull%2C%22phone_number%22%3Anull%7D%2C%22meta%22%3A%7B%22token%22%3A%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwXC9hcGlcL2F1dGhcL2dvb2dsZVwvY2FsbGJhY2siLCJpYXQiOjE0ODg5OTYwMDYsImV4cCI6MTQ4ODk5OTYwNiwibmJmIjoxNDg4OTk2MDA2LCJqdGkiOiIxZGMyZjY4NDBkNmVjYzZkMWZkNDg4ZmUzMjJjMWJlNiJ9.5IU8FihoOf0V8AtzMa32tRgJk-dihaIUMHp6GiOZs7M%22%7D%7D&success=true#
```
Example decoded url:
```
{"data":{"id":2,"name":"Laurendy Lam","email":"lamlaurendy@gmail.com","username":null,"phone_number":null},"meta":{"token":"eyJ0eXAiOi …
```

Include user login response

---

app/Http/Kernel.php
app/Http/Middleware/VerifyOTP.php
app/Transformers/UserTransformer.php
app/User.php
routes/api.php

- adds an otp middlware
- hides the otp attribute from sending it to the client
- only an unlocked user can access resources
*PLEASE MERGE ONLY WHEN FRONT END OTP IS COMPLETE*

Otp middleware

---

app/Http/Controllers/Transfer/User/ReceiveController.php
app/Transformers/TransferTransformer.php
phpunit.xml
tests/feature/TransferTest.php
tests/unit/TransfersTest.php

- implement receive controller logic
- deposit transfer
- receive transfer test
so far a user can receive a transfer as long as the transfer token's status is pending . Once a transfer is received the transfer will be complete.
*Please review https://github.com/Project-Epsilon/server/pull/46 first*

EP-6 EP-55 Transfer receive controller

---

app/Http/Controllers/Wallet/WalletController.php
app/Transformers/TransactionTransformer.php
app/Transformers/TransferTransformer.php
app/Transformers/WalletTransformer.php

Appending transaction log to wallets.

Add transactions to wallets

---

app/Transformers/ContactTransformer.php

Remove the int conversion for phone numbers.

Update contacts transformer.

---

app/Classes/WalletManager.php
tests/feature/TransferTest.php
tests/unit/WalletManagerTest.php

There was a little problem with floating point numbers. It goes back to COMP 248 where I forgot that floating point number must be compared with a small number.

Decimal check on currency + test.

---

app/Http/Controllers/User/ContactController.php
tests/feature/ContactTest.php

Modify contacts validation and adjusted testing.

Update contacts validation.

---

app/Classes/NexmoMessage.php
app/Http/Controllers/Auth/OTPController.php
app/Providers/NexmoServiceProvider.php

for better encapsulation of data

use of nexmo message class

---

resources/views/email/layout.blade.php
resources/views/email/templates/payment.blade.php

recipient transfer email template

new payment template

---

app/Jobs/SendTransfer.php
app/Transformers/CurrencyTransformer.php
app/Transformers/TransferTransformer.php
app/Transformers/WalletTransformer.php
tests/feature/WalletTest.php

- removes the currency symbol from the balance.
- adds symbol to currencies.

remove currency symbol

---

app/Http/Controllers/Auth/LoginController.php
tests/feature/LoginTest.php

EP-93 EP-95 Logout controller

---

app/Http/Controllers/Transfer/User/TransferController.php
app/Transformers/TransferTransformer.php
app/User.php
app/Wallet.php
database/factories/ModelFactory.php
database/migrations/2017_02_17_184025_create_transfers_table.php
routes/api.php
tests/feature/UserTransferTest.php

- added relations to models wallet and user to get all transfers.
- update transfers database
- implemeneted transfer controller for users
- added additional route to get transfer by token
- added transfers test

Transfers api

---

app/Http/Controllers/Controller.php
app/Http/Controllers/User/UserController.php
app/SocialAccount.php
tests/feature/UserTest.php

- delete account test
- implemented in user controller delete account
- add new success response

EP-16 Delete account

---

app/Http/Controllers/Transfer/User/TransferController.php
routes/api.php
tests/feature/UserTransferTest.php

The client can now query for pending out transfers.

Pending out transfers

---

app/Http/Controllers/Wallet/WalletController.php
tests/feature/WalletTest.php

The user may now update the order of wallets shown and the visibliy of
each wallet.

implement update wallet with test

---

app/Http/Controllers/Transfer/User/ReceiveController.php
routes/api.php
tests/feature/TransferTest.php

A user may cancel a transfer and have it re-deposit back into the sender's wallet.

Cancel transfer

---

app/Classes/WalletManager.php
app/Http/Controllers/Transfer/User/ReceiveController.php
app/Http/Controllers/Transfer/User/SendController.php
app/Transaction.php
database/migrations/2017_02_17_013500_create_transactions_table.php
tests/unit/WalletManagerTest.php

Users will be able to see transfers log to their wallet.

Transfer Logging

---

app/Transformers/TransferTransformer.php

The api now exposes wallet ids.

add wallet ids to transfer transformer

---

app/BankTransfer.php
app/Classes/WalletManager.php
app/Currency.php
app/Http/Controllers/Transfer/Bank/DepositController.php
app/Http/Controllers/Transfer/Bank/WithdrawalController.php
app/Mail/NewPayment.php
app/Providers/PayPalServiceProvider.php
database/migrations/2017_02_22_202955_create_bank_transfers_table.php
tests/unit/BankTransferTest.php

Record bank transfer

---

app/Http/Controllers/Transfer/Bank/TransferController.php
app/Http/Controllers/Transfer/Bank/WithdrawalController.php
app/Jobs/SendTransfer.php
app/Transformers/BankTransferTransformer.php
app/User.php
database/factories/ModelFactory.php
tests/feature/BankTransferTest.php

- users can now request bank transfer information

Bank transfers request

---

app/Http/Middleware/VerifyOTP.php
tests/unit/VerifyOTPMiddlewareTest.php

- add a correct response in the middleware
- testing done for middleware

add test for verify otp middleware

---

config/app.php

- the transfer link is customized without changing the code, configurable in the env file.

change transfer link in app.php

---

resources/views/welcome.blade.php

- customised landing page for mBarter server.

landing page

---

app/Http/Controllers/Transfer/Bank/DepositController.php

corrects the non defined wallet object error

wallet deposit controller correction

---

app/Classes/WalletManager.php
tests/unit/WalletManagerTest.php

- adding bank transfer to transaction logging

add more transaction code coverage

---

app/Http/Controllers/Auth/OTPController.php
app/Http/Controllers/User/ContactController.php
app/Http/Controllers/Wallet/WalletController.php

- no more string ok responses
- include wallet transactions in single wallet request

upgrade success response to use methods

---

app/Http/Controllers/Transfer/Bank/WithdrawalController.php
app/Providers/PayPalServiceProvider.php

- the withdrawal process pushed an invalid id to the bank transfer model.

Withdrawal bug

---

.gitignore
app/Http/Controllers/Transfer/User/TransferController.php
app/Http/Controllers/User/ContactController.php
tests/feature/BankTransferTransactionTest.php
tests/feature/ContactTest.php
tests/feature/UserTransferTest.php
tests/unit/UserTest.php

- Completes most coverage tests for contacts controller, user model and user transfer tests.

Addition coverage for test spint 4.
